export const aboutItems = [
  {
    id: 'performance',
    icon: 'zap',
    title: 'Performance Engineering',
    metric: '-48% load time',
    problem:
      'Slow applications caused user frustration and drop-offs due to inefficient rendering.',
    solution:
      'Optimized rendering cycles, caching strategies and eliminated unnecessary re-renders.',
    result: 'Reduced load time by 48% and improved user retention.',
  },
  {
    id: 'saas',
    icon: 'layers',
    title: 'SaaS Architecture',
    metric: '+120% scalability',
    problem: 'System could not handle user growth, causing instability.',
    solution: 'Designed multi-tenant architecture with scalable modules.',
    result: 'Handled 2x more users with stable performance.',
  },
  {
    id: 'ai',
    icon: 'brain',
    title: 'AI Integration',
    metric: '+65% automation',
    problem: 'Manual workflows slowed operations and reduced efficiency.',
    solution: 'Integrated AI for automation and intelligent decision-making.',
    result: 'Increased automation rate by 65%.',
  },
  {
    id: 'backend',
    icon: 'server',
    title: 'Backend Optimization',
    metric: '-35% response time',
    problem: 'Slow APIs impacted overall application performance.',
    solution: 'Optimized queries and reduced bottlenecks.',
    result: 'Improved response time significantly.',
  },
  {
    id: 'database',
    icon: 'database',
    title: 'Database Optimization',
    metric: '+40% efficiency',
    problem: 'Inefficient queries overloaded the system.',
    solution: 'Redesigned schema and indexing strategy.',
    result: 'Faster queries and lower resource usage.',
  },
  {
    id: 'frontend',
    icon: 'code',
    title: 'Frontend Architecture',
    metric: '+30% UX improvement',
    problem: 'Poor UI responsiveness impacted user experience.',
    solution: 'Refactored components and improved state handling.',
    result: 'Smoother interactions and better UX.',
  },
  {
    id: 'analytics',
    icon: 'chart',
    title: 'Analytics Systems',
    metric: '+50% data clarity',
    problem: 'Lack of visibility into business data.',
    solution: 'Built real-time dashboards and metrics.',
    result: 'Better decision-making and insights.',
  },
  {
    id: 'infra',
    icon: 'settings',
    title: 'Infrastructure',
    metric: '+70% reliability',
    problem: 'Frequent downtime affected business operations.',
    solution: 'Improved deployment pipelines and monitoring.',
    result: 'More stable production systems.',
  },
  {
    id: 'api',
    icon: 'cpu',
    title: 'API Design',
    metric: '+45% efficiency',
    problem: 'Redundant API calls reduced performance.',
    solution: 'Redesigned endpoints and data flow.',
    result: 'Cleaner architecture and faster responses.',
  },
  {
    id: 'growth',
    icon: 'rocket',
    title: 'Growth Engineering',
    metric: '+30% engagement',
    problem: 'Low user engagement and retention.',
    solution: 'Optimized UX and performance.',
    result: 'Higher engagement metrics.',
  },
  {
    id: 'monitoring',
    icon: 'activity',
    title: 'Monitoring',
    metric: '+60% visibility',
    problem: 'Lack of system observability.',
    solution: 'Implemented logs and monitoring tools.',
    result: 'Faster debugging and issue resolution.',
  },
  {
    id: 'data',
    icon: 'flow',
    title: 'Data Flow Optimization',
    metric: '+35% speed',
    problem: 'Slow data processing pipelines.',
    solution: 'Optimized async flows and pipelines.',
    result: 'Faster data processing and performance.',
  },
];
